### ISSUE TITLE
Can't not register

### ISSUE THREAD

**Issue by pum-k** [ezzio/project_management_horenso#142]
Anh thu dang ky nhung khong co gi xay ra ca ngoai console.log ra cai object form

![Peek 2022-01-18 17-41](https://user-images.githubusercontent.com/75214138/149922218-908e007b-ab3e-40bb-a0d5-148219cf4329.gif)

**Comment by mrminhb** [comment]
Lần trước em với a Thắng test thì anh Thắng bảo là phía backend có vấn đề gì á
