### ISSUE TITLE
Redirect về dashboard page thay vì 404 page sau khi tạo project

### ISSUE THREAD

**Issue by lcnhut070200** [ezzio/project_management_horenso#244]
<img width="1552" alt="Screen Shot 2022-03-16 at 10 01 49 PM" src="https://user-images.githubusercontent.com/58385680/158620831-841a6e27-0043-452e-b3fb-c4dc0d93bfb9.png">

**Comment by nguyendang127** [comment]
nhựt làm rồi 🥰
