### ISSUE TITLE
Fix trang Storage

### ISSUE THREAD

**Issue by pum-k** [ezzio/project_management_horenso#67]
# Nội dung cần thực hiện

![Screenshot 2021-10-04 205037](https://user-images.githubusercontent.com/75214138/135883738-6519c3c0-0ba7-44c0-8ca6-1a64c5507ac7.png)

1. Cần loại bỏ border, Icon search tương đối to
2. Submit là gì?. Điều chỉnh size và radius của btn
3. icon filter không được xuống hàng
4. thay name -> icon avatar

Mẫu: https://dribbble.com/shots/11698088-Cloud-Drive-Files

> Cần hỗ trợ gì nhắn trực tiếp ở đây

**Comment by lcnhut070200** [comment]
Đề nghị close!!!
