### ISSUE TITLE
Fix trang conversation

### ISSUE THREAD

**Issue by pum-k** [ezzio/project_management_horenso#68]
# Nội dung cần thực hiện

![Screenshot 2021-10-04 210140](https://user-images.githubusercontent.com/75214138/135885478-3c7691d3-3538-4e9e-a0cd-c555be307e1b.png)

1. Cần xử lý khi tên người dùng và thời gian tương đối xa nhau, thời gian cần update theo moment (ex: a few second)
2. Text chưa căn giữa
3. đổi input thành textarea nhỏ lại 1 dòng. Khi chat nhiều hơn 1 dòng mới mở rộng. (Lên messenger xem thử)
4. hover bị lỗi
5. fix khoảng cách giữa 2 tin nhắn vì quá xa nhau

> Thắc mắc hỏi trực tiếp trên đây

**Comment by nguyendang127** [comment]
Ok v tui fix
